# Generated by Django 3.2.7 on 2021-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_student_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pincode',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='student_photos'),
        ),
    ]
