# Generated by Django 3.2.7 on 2021-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20210929_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
