# Generated by Django 3.2.7 on 2021-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20210930_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='compulsory',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
