# Generated by Django 3.2.7 on 2021-09-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='academiccalendar',
            field=models.FileField(null=True, upload_to='academiccalendar'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('message', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.semester')),
            ],
        ),
    ]
