# Generated by Django 3.2.7 on 2021-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20210930_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='currentsem',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
