# Generated by Django 3.2.5 on 2022-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tips',
            field=models.TextField(null=True),
        ),
    ]
